package com.example.BACKEND.catalogue.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Persistent insight card generated by the AgentOrchestrator.
 *
 * State machine (status field):
 *   AWAITING_CONFIRMATION → unread; shown in the inbox feed
 *   COMPLETED             → user marked as read; hidden on refresh, positive signal for learning
 *   DECLINED              → user dismissed as irrelevant; hidden on refresh, negative signal
 *   EXPIRED               → TTL passed or replaced by a new Refresh Insights run
 *
 * The JSON columns (metricHighlights, reasons, strategies) store
 * serialised lists. Deserialisation happens in the service layer.
 */
@Entity
@Table(name = "insight_cards",
        indexes = {
            @Index(name = "idx_insight_client_status",
                   columnList = "client_id, status"),
            @Index(name = "idx_insight_client_recent",
                   columnList = "client_id, generated_at")
        })
public class InsightCardEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @Column(name = "client_id", nullable = false)
    private String clientId;

    @Column(name = "title", nullable = false, columnDefinition = "TEXT")
    private String title;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    @Column(name = "impact_level")
    private String impactLevel;

    @Column(name = "badge")
    private String badge;

    @Column(name = "agent_name")
    private String agentName;

    @Column(name = "confidence")
    private Integer confidence;

    /** Serialised JSON array of {label, value} objects */
    @Column(name = "metric_highlights", columnDefinition = "TEXT")
    private String metricHighlights;

    /** Serialised JSON array of reason strings */
    @Column(name = "reasons", columnDefinition = "TEXT")
    private String reasons;

    /** Serialised JSON array of strategy strings */
    @Column(name = "strategies", columnDefinition = "TEXT")
    private String strategies;

    /**
     * Serialised JSON array of actual column names the LLM cited as sources.
     * e.g. ["product_category","is_returned","total_revenue"]
     * Used to verify that insights reference real columns.
     */
    @Column(name = "source_columns", columnDefinition = "TEXT")
    private String sourceColumns;

    /**
     * Compact snapshot of the raw data rows the LLM saw when generating this card.
     * Stored as JSON — enables "Show Evidence" for manual accuracy verification.
     */
    @Column(name = "raw_evidence", columnDefinition = "TEXT")
    private String rawEvidence;

    /** Serialised chart spec JSON for the insight card (rendered by frontend). */
    @Column(name = "chart_spec", columnDefinition = "TEXT")
    private String chartSpec;

    /**
     * AWAITING_CONFIRMATION | DECLINED | COMPLETED | EXPIRED
     */
    @Column(name = "status", nullable = false)
    private String status = "AWAITING_CONFIRMATION";

    @Column(name = "generated_at")
    private LocalDateTime generatedAt;

    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    @Column(name = "acted_at")
    private LocalDateTime actedAt;

    // ── Getters / Setters ─────────────────────────────────────────────────────

    public UUID getId()                        { return id; }
    public void setId(UUID id)                 { this.id = id; }

    public String getClientId()                { return clientId; }
    public void setClientId(String clientId)   { this.clientId = clientId; }

    public String getTitle()                   { return title; }
    public void setTitle(String title)         { this.title = title; }

    public String getDescription()             { return description; }
    public void setDescription(String v)       { this.description = v; }

    public String getImpactLevel()             { return impactLevel; }
    public void setImpactLevel(String v)       { this.impactLevel = v; }

    public String getBadge()                   { return badge; }
    public void setBadge(String v)             { this.badge = v; }

    public String getAgentName()               { return agentName; }
    public void setAgentName(String v)         { this.agentName = v; }

    public Integer getConfidence()             { return confidence; }
    public void setConfidence(Integer v)       { this.confidence = v; }

    public String getMetricHighlights()        { return metricHighlights; }
    public void setMetricHighlights(String v)  { this.metricHighlights = v; }

    public String getReasons()                 { return reasons; }
    public void setReasons(String v)           { this.reasons = v; }

    public String getStrategies()              { return strategies; }
    public void setStrategies(String v)        { this.strategies = v; }

    public String getSourceColumns()           { return sourceColumns; }
    public void setSourceColumns(String v)     { this.sourceColumns = v; }

    public String getRawEvidence()             { return rawEvidence; }
    public void setRawEvidence(String v)       { this.rawEvidence = v; }

    public String getChartSpec()               { return chartSpec; }
    public void setChartSpec(String v)         { this.chartSpec = v; }

    public String getStatus()                  { return status; }
    public void setStatus(String v)            { this.status = v; }

    public LocalDateTime getGeneratedAt()      { return generatedAt; }
    public void setGeneratedAt(LocalDateTime v){ this.generatedAt = v; }

    public LocalDateTime getExpiresAt()        { return expiresAt; }
    public void setExpiresAt(LocalDateTime v)  { this.expiresAt = v; }

    public LocalDateTime getActedAt()          { return actedAt; }
    public void setActedAt(LocalDateTime v)    { this.actedAt = v; }
}
