import crypto from "node:crypto";

/**
 * CSRF `state` generation and constant-time comparison for the browser handoff
 * login flow. (No OAuth, no PKCE — `state` is the only anti-forgery value, and
 * it is generated by the MCP and verified at the loopback callback.)
 */

function base64Url(buffer: Buffer): string {
  return buffer
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}

/** Create an opaque, high-entropy `state` value. */
export function createState(): string {
  return base64Url(crypto.randomBytes(24));
}

/** Constant-time string comparison to validate the returned `state`. */
export function safeEquals(a: string, b: string): boolean {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  if (bufA.length !== bufB.length) {
    return false;
  }
  return crypto.timingSafeEqual(bufA, bufB);
}
