spring.application.name=BACKEND

# OpenAI API Configuration
openai.api.key=xxxxxxx
openai.model=gpt-4o-mini

spring.datasource.url=jdbc:postgresql://localhost:5432/admindb
spring.datasource.username=postgres
spring.datasource.password=Champu1$

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.indent-output=true
management.endpoints.web.exposure.include=mappings

server.port=5000