spring.application.name=BACKEND

# OpenAI API Configuration
openai.api.key=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
openai.model=gpt-4o-mini

spring.datasource.url=jdbc:postgresql://localhost:5432/admindb
spring.datasource.username=postgres
spring.datasource.password=Champu1$

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.indent-output=true
management.endpoints.web.exposure.include=mappings

server.port=5000