-- ============================================================
-- Phase X — Chart Spec Storage (Insight Cards)
-- ============================================================
-- Adds an optional chart_spec JSON blob per insight card.
-- Rendered by frontend; generated by backend mapper.
-- ============================================================

ALTER TABLE insight_cards
    ADD COLUMN IF NOT EXISTS chart_spec TEXT;

